// Form field definitions for HSTU Karate Dojo Form
// Field IDs mapped from the PDF AcroForm fields (see fillForm.js)

export interface FormFieldDef {
  id: string;
  pdfFieldId: string;
  label: string;
  labelBn?: string;
  placeholder?: string;
  type: "text" | "textarea" | "date" | "email" | "tel" | "number" | "select";
  required: boolean;
  maxLength?: number;
  section: string;
  helpText?: string;
  readOnly?: boolean;
  defaultValue?: string;
  options?: { value: string; label: string }[];
}

export const FORM_SECTIONS = [
  { id: "basic", title: "Basic Information", icon: "User" },
  { id: "contact", title: "Contact Details", icon: "Phone" },
  { id: "student", title: "Student Details", icon: "GraduationCap" },
  { id: "family", title: "Family Information", icon: "Users" },
  { id: "physical", title: "Physical Details", icon: "Activity" },
  { id: "activities", title: "Activities & Motive", icon: "Target" },
  { id: "branch", title: "Branch & Registration", icon: "MapPin" },
  { id: "images", title: "Photo & Signature", icon: "Camera" },
] as const;

export const FORM_FIELDS: FormFieldDef[] = [
  // === Basic Information ===
  {
    id: "name_en",
    pdfFieldId: "text_2gcgy",
    label: "Full Name (English)",
    labelBn: "নাম (ইংরেজি)",
    placeholder: "Enter your full name in English",
    type: "text",
    required: true,
    maxLength: 100,
    section: "basic",
  },
  {
    id: "name_bn",
    pdfFieldId: "text_3zwog",
    label: "Full Name (Bangla)",
    labelBn: "নাম (বাংলা)",
    placeholder: "বাংলায় পূর্ণ নাম লিখুন",
    type: "text",
    required: true,
    maxLength: 100,
    section: "basic",
  },
  {
    id: "dob",
    pdfFieldId: "text_8qsa",
    label: "Date of Birth",
    labelBn: "জন্ম তারিখ",
    placeholder: "DD/MM/YYYY",
    type: "date",
    required: true,
    section: "basic",
  },
  {
    id: "nationality",
    pdfFieldId: "text_10itmk",
    label: "Nationality",
    labelBn: "জাতীয়তা",
    placeholder: "e.g., Bangladeshi",
    type: "text",
    required: true,
    maxLength: 50,
    section: "basic",
    defaultValue: "Bangladeshi",
  },
  {
    id: "religion",
    pdfFieldId: "text_32ijag",
    label: "Religion",
    labelBn: "ধর্ম",
    placeholder: "e.g., Islam",
    type: "text",
    required: true,
    maxLength: 50,
    section: "basic",
  },
  {
    id: "nid",
    pdfFieldId: "text_11eyhm",
    label: "NID / Birth Certificate / Passport No.",
    labelBn: "জাতীয় পরিচয়পত্র / জন্ম নিবন্ধন / পাসপোর্ট নং",
    placeholder: "Enter your ID number",
    type: "text",
    required: true,
    maxLength: 50,
    section: "basic",
  },

  // === Contact Details ===
  {
    id: "present_address",
    pdfFieldId: "text_6qwqa",
    label: "Present Address",
    labelBn: "বর্তমান ঠিকানা",
    placeholder: "Enter your current address",
    type: "textarea",
    required: true,
    maxLength: 200,
    section: "contact",
  },
  {
    id: "permanent_address",
    pdfFieldId: "text_7rkjm",
    label: "Permanent Address",
    labelBn: "স্থায়ী ঠিকানা",
    placeholder: "Enter your permanent address",
    type: "textarea",
    required: true,
    maxLength: 200,
    section: "contact",
  },
  {
    id: "mobile",
    pdfFieldId: "text_12jovw",
    label: "Mobile Number",
    labelBn: "মোবাইল নম্বর",
    placeholder: "01XXXXXXXXX",
    type: "tel",
    required: true,
    maxLength: 15,
    section: "contact",
  },
  {
    id: "email",
    pdfFieldId: "text_33yqgf",
    label: "Email Address",
    labelBn: "ইমেইল",
    placeholder: "your.email@example.com",
    type: "email",
    required: false,
    maxLength: 100,
    section: "contact",
  },
  {
    id: "emergency_contact",
    pdfFieldId: "text_13xzow",
    label: "Emergency Contact Number",
    labelBn: "জরুরি যোগাযোগ নম্বর",
    placeholder: "01XXXXXXXXX",
    type: "tel",
    required: true,
    maxLength: 15,
    section: "contact",
  },
  {
    id: "emergency_relation",
    pdfFieldId: "text_35dbko",
    label: "Relationship with Emergency Contact",
    labelBn: "জরুরি যোগাযোগকারীর সাথে সম্পর্ক",
    placeholder: "e.g., Mother, Father, Brother",
    type: "text",
    required: true,
    maxLength: 50,
    section: "contact",
  },

  // === Student Details ===
  {
    id: "occupation",
    pdfFieldId: "text_14frao",
    label: "Occupation",
    labelBn: "পেশা",
    placeholder: "e.g., Student",
    type: "text",
    required: true,
    maxLength: 50,
    section: "student",
    defaultValue: "Student",
  },
  {
    id: "institution",
    pdfFieldId: "text_15nxit",
    label: "Name of Institution",
    labelBn: "প্রতিষ্ঠানের নাম",
    placeholder: "Enter your institution name",
    type: "text",
    required: true,
    maxLength: 100,
    section: "student",
  },
  {
    id: "level_class",
    pdfFieldId: "text_16hvzz",
    label: "Level / Class",
    labelBn: "শ্রেণী / স্তর",
    placeholder: "e.g., Class 10, BSc 2nd Year",
    type: "text",
    required: true,
    maxLength: 50,
    section: "student",
  },
  {
    id: "roll_id",
    pdfFieldId: "text_17wput",
    label: "ID / Roll Number",
    labelBn: "আইডি / রোল নম্বর",
    placeholder: "Enter your student ID or roll number",
    type: "text",
    required: true,
    maxLength: 50,
    section: "student",
  },
  {
    id: "faculty_dept",
    pdfFieldId: "text_36rbtt",
    label: "Faculty / Department / Section",
    labelBn: "অনুষদ / বিভাগ / শাখা",
    placeholder: "e.g., Science / Physics / A",
    type: "text",
    required: false,
    maxLength: 100,
    section: "student",
  },

  // === Family Information ===
  {
    id: "father_name",
    pdfFieldId: "text_4juqg",
    label: "Father's Name (English)",
    labelBn: "পিতার নাম (ইংরেজি)",
    placeholder: "Enter father's full name",
    type: "text",
    required: true,
    maxLength: 100,
    section: "family",
  },
  {
    id: "mother_name",
    pdfFieldId: "text_5eyrb",
    label: "Mother's Name (English)",
    labelBn: "মাতার নাম (ইংরেজি)",
    placeholder: "Enter mother's full name",
    type: "text",
    required: true,
    maxLength: 100,
    section: "family",
  },
  {
    id: "father_occupation",
    pdfFieldId: "text_26lzic",
    label: "Father's Occupation",
    labelBn: "পিতার পেশা",
    placeholder: "e.g., Businessman",
    type: "text",
    required: true,
    maxLength: 50,
    section: "family",
  },
  {
    id: "mother_occupation",
    pdfFieldId: "text_27orzd",
    label: "Mother's Occupation",
    labelBn: "মাতার পেশা",
    placeholder: "e.g., Teacher",
    type: "text",
    required: true,
    maxLength: 50,
    section: "family",
  },

  // === Physical Details ===
  {
    id: "age",
    pdfFieldId: "text_28tdwn",
    label: "Age",
    labelBn: "বয়স",
    placeholder: "e.g., 16",
    type: "text",
    required: true,
    maxLength: 5,
    section: "physical",
  },
  {
    id: "height",
    pdfFieldId: "text_9hslb",
    label: "Height",
    labelBn: "উচ্চতা",
    placeholder: "e.g., 5'8\"",
    type: "text",
    required: true,
    maxLength: 20,
    section: "physical",
  },
  {
    id: "weight",
    pdfFieldId: "text_29lyqz",
    label: "Weight",
    labelBn: "ওজন",
    placeholder: "e.g., 58 kg",
    type: "text",
    required: true,
    maxLength: 20,
    section: "physical",
  },
  {
    id: "blood_group",
    pdfFieldId: "text_30ipgl",
    label: "Blood Group",
    labelBn: "রক্তের গ্রুপ",
    placeholder: "Select your blood group",
    type: "select",
    required: true,
    section: "physical",
    options: [
      { value: "A+", label: "A+" },
      { value: "A-", label: "A-" },
      { value: "B+", label: "B+" },
      { value: "B-", label: "B-" },
      { value: "AB+", label: "AB+" },
      { value: "AB-", label: "AB-" },
      { value: "O+", label: "O+" },
      { value: "O-", label: "O-" },
    ],
  },
  {
    id: "bmi",
    pdfFieldId: "text_31mqrf",
    label: "BMI (Optional)",
    labelBn: "বিএমআই (ঐচ্ছিক)",
    placeholder: "e.g., 21.5",
    type: "text",
    required: false,
    maxLength: 10,
    section: "physical",
    helpText: "Body Mass Index - will be auto-calculated if height/weight are provided",
  },

  // === Activities & Motive ===
  {
    id: "activities_first",
    pdfFieldId: "text_37umsg",
    label: "Activities (Short)",
    labelBn: "কার্যক্রম (সংক্ষিপ্ত)",
    placeholder: "e.g., Football, Reading",
    type: "text",
    required: false,
    maxLength: 20,
    section: "activities",
    helpText: "Max 20 characters — brief summary of activities",
  },
  {
    id: "activities_last",
    pdfFieldId: "text_18yymw",
    label: "Activities (Detailed)",
    labelBn: "কার্যক্রম (বিস্তারিত)",
    placeholder: "Describe your activities, hobbies, and interests in detail...",
    type: "textarea",
    required: false,
    maxLength: 200,
    section: "activities",
    helpText: "Max 200 characters — detailed description of your activities",
  },
  {
    id: "motive_first",
    pdfFieldId: "text_19szou",
    label: "Motive for Training (Part 1)",
    labelBn: "প্রশিক্ষণের উদ্দেশ্য (অংশ ১)",
    placeholder: "Why do you want to learn karate? Describe your motivation...",
    type: "textarea",
    required: true,
    maxLength: 200,
    section: "activities",
    helpText: "Max 200 characters — first part of your motive",
  },
  {
    id: "motive_last",
    pdfFieldId: "text_20wqom",
    label: "Motive for Training (Part 2)",
    labelBn: "প্রশিক্ষণের উদ্দেশ্য (অংশ ২)",
    placeholder: "Continue describing your goals and expectations...",
    type: "textarea",
    required: false,
    maxLength: 200,
    section: "activities",
    helpText: "Max 200 characters — continue your motive if needed",
  },

  // === Branch & Registration ===
  {
    id: "registration_no",
    pdfFieldId: "text_23aqm",
    label: "Registration Number",
    labelBn: "নিবন্ধন নম্বর",
    placeholder: "Leave blank — assigned by authority",
    type: "text",
    required: false,
    maxLength: 50,
    section: "branch",
    readOnly: true,
    defaultValue: "",
    helpText: "This will be assigned by the authority — leave blank",
  },
  {
    id: "dojo_branch",
    pdfFieldId: "text_24fdfi",
    label: "Karate Dojo Branch",
    labelBn: "কারাতে ডোজো শাখা",
    placeholder: "e.g., HSTU Main Branch",
    type: "text",
    required: true,
    maxLength: 100,
    section: "branch",
  },
  {
    id: "dojo_location",
    pdfFieldId: "text_25csjw",
    label: "Karate Dojo Location",
    labelBn: "কারাতে ডোজো অবস্থান",
    placeholder: "e.g., HSTU Campus",
    type: "text",
    required: true,
    maxLength: 100,
    section: "branch",
  },
  {
    id: "signature_date",
    pdfFieldId: "text_38egdr",
    label: "Signature Date",
    labelBn: "স্বাক্ষরের তারিখ",
    placeholder: "Auto-filled with today's date",
    type: "date",
    required: true,
    section: "branch",
    helpText: "Auto-filled with today's date",
  },
  {
    id: "authority_date",
    pdfFieldId: "text_39tajn",
    label: "Authority Signature Date",
    labelBn: "কর্তৃপক্ষের স্বাক্ষরের তারিখ",
    placeholder: "Leave blank — for authority use",
    type: "text",
    required: false,
    readOnly: true,
    defaultValue: "",
    section: "branch",
    helpText: "This will be filled by the authority — leave blank",
  },
];

// Image positions for the PDF
export const PHOTO_BOX = {
  x: 477.36,
  y: 128.88,
  width: 83.52,
  height: 90,
};

export const SIGNATURE_POSITIONS = {
  student: {
    x: 150,
    y: 100,
    width: 150,
    height: 50,
  },
  parent: {
    x: 150,
    y: 50,
    width: 150,
    height: 50,
  },
};

export const PAGE_DIMENSIONS = {
  width: 595.389,
  height: 841.918,
};

// Image validation constants
export const IMAGE_CONSTRAINTS = {
  photo: {
    maxSizeMB: 5,
    maxSizeBytes: 5 * 1024 * 1024,
    acceptedTypes: ["image/jpeg", "image/png", "image/jpg"],
    minWidth: 150,
    minHeight: 180,
    maxWidth: 2000,
    maxHeight: 2400,
    recommendedWidth: 300,
    recommendedHeight: 360,
    aspectRatioMin: 0.7,   // width/height min
    aspectRatioMax: 0.95,  // width/height max (portrait)
  },
  signature: {
    maxSizeMB: 2,
    maxSizeBytes: 2 * 1024 * 1024,
    acceptedTypes: ["image/jpeg", "image/png", "image/jpg"],
    minWidth: 100,
    minHeight: 30,
    maxWidth: 1500,
    maxHeight: 500,
    recommendedWidth: 400,
    recommendedHeight: 150,
    aspectRatioMin: 1.5,   // width/height min (landscape)
    aspectRatioMax: 6.0,   // width/height max
  },
};
